export enum CharacterCreationErrorCode {
    CHARACTER_NAME_INVALID = 'CHARACTER_NAME_INVALID',
    CHARACTER_NAME_TAKEN = 'CHARACTER_NAME_TAKEN',
    CHARACTER_AGE_OUT_OF_RANGE = 'CHARACTER_AGE_OUT_OF_RANGE',
    CHARACTER_ALREADY_EXISTS = 'CHARACTER_ALREADY_EXISTS',
    STARTING_LOCATION_UNAVAILABLE = 'STARTING_LOCATION_UNAVAILABLE',
    BAD_USER_INPUT = 'BAD_USER_INPUT',
}
