export enum AuthErrorCode {
    UNAUTHENTICATED = 'UNAUTHENTICATED',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    SESSION_REVOKED = 'SESSION_REVOKED',
    LOGIN_TICKET_INVALID = 'LOGIN_TICKET_INVALID',
}
